<a href="https://colab.research.google.com/github/gpsworld/Deep_learning_lab/blob/main/DL_EXPERIMENT_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

def mcp_neuron(X1, X2, W1, W2, threshold):
    weighted_sum = X1 * W1 + X2 * W2
    return 1 if weighted_sum >= threshold else 0

input_combinations = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

W1, W2 = 1, 1
threshold = 2
table = []

for inputs in input_combinations:
    X1, X2 = inputs
    output = mcp_neuron(X1, X2, W1, W2, threshold)
    print("Neuron Fires!" if output == 1 else "Neuron stays deactivated")
    table.append([X1, X2, output])

table = np.array(table)

print("X1 X2 Output")
print(table)


Neuron stays deactivated
Neuron stays deactivated
Neuron stays deactivated
Neuron Fires!
X1 X2 Output
[[0 0 0]
 [0 1 0]
 [1 0 0]
 [1 1 1]]
